actions:
  1:
    action: close
    description: "Close indices"
    options:
      delete_aliases: False
      continue_if_exception: True
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: regex
      value: ${INDEX_PATTERN}
    - filtertype: opened
      exclude: False
  2:
    action: restore
    description: "Restore from snapshot"
    options:
      repository: ${SNAPSHOT_REPOSITORY_NAME}
      # Leaving name blank will result in restoring the most recent snapshot by age
      name: ${SNAPSHOT_NAME}
      # Leaving indices blank will result in restoring all indices in the snapshot
      indices: ${INDICES}
      ignore_unavailable: False
      include_global_state: False
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: True
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: state
      state: SUCCESS
      exclude:
    - filtertype: pattern
      kind: regex
      value: '^.*$'
      exclude:
