---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts: ${ES_HOST}
  port:
  url_prefix:
  use_ssl: ${TLS_HTTP_ENABLED}
  certificate: ${ROOT_CA_CERTIFICATE}
  client_cert:
  client_key:
  ssl_no_validate: ${SSL_NO_VALIDATE}
  username: ${ES_USERNAME}
  password: ${ES_PASSWORD}
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']